print("Exercicio 2.1")
print("1", "2", "3", "4", "5", "++", sep='---', end='\n')
print("Exercicio 2.2")
print("\"Estoy\"")
print("\"'Algunos símbolos'\"")
print("\"''Son difíciles de imprimir: '/'\"''\"")
print("Exercicio 2.3")
print("I'm Monty Python.")
print("Exercicio 2.4")
resultado = ((2 + 3) / (2 * 5)) ** 2
print(resultado)
